
title: Vienna.rb - User group for Viennese rubyists
description: organizing meetups for Ruby and Rails developers in and around Vienna, Austria.

baseurl: /viennarb
url:  https://geraldb.github.io/viennarb


### let's use the minima theme (see https://github.com/jekyll/minima)

theme: minima


### exclude the instructions / write-up in the README.md

exclude:
- README.md
